### ISSUE TITLE
Make tutorial accessible

### ISSUE THREAD

**Issue by neothemachine** [CSTARS/ckanext-ecosis#1]
It would be nice if the tutorial would be living somewhere online (not just inside git). In the meantime: https://rawgit.com/CSTARS/ckanext-esis/master/tutorial/index.html (which however is partly broken)

**Comment by jrmerz** [comment]
the tutorial is live here: tutorial.ecospectra.org.  You can serve locally with any static webserver.  What seems to be broken?

**Comment by neothemachine** [comment]
Ah ok, can you link that from the README.md maybe? Hard to find otherwise, or did I miss a link somewhere?
