### ISSUE TITLE
pushing unnamed dataset throws error

### ISSUE THREAD

**Issue by ckingdon** [CSTARS/ckanext-ecosis#12]
The user tried to push a dataset had not yet been named. This error (below) came back. Better to catch this with a reminder that that the dataset can't be pushed to search until it has been named.

Oooh no, badness :(
Error: ValidationError:{u'Name': u'Missing value'}
Please help us fix bugs by reporting them here on GitHub! 
Copy and paste message below into GitHub Issue:
- Package ID:
- Message: ValidationError:{u'Name': u'Missing value'}
- Code: 6
- User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
- commit: 36ff100071adf1737ac337cdee1b4ce72729c0a7
- version: v1.2-72-g36ff100
- branch: dev

**Comment by jrmerz** [comment]
@ckingdon ya, that 'Create Dataset' button is styled disabled but looks like it still lets you click on it.  By default nothing should happen when it's clicked and you haven't provided a title.

**Comment by jrmerz** [comment]
Pushed fix to dev.
