### ISSUE TITLE
can't link for Potato Virus Y

### ISSUE THREAD

**Issue by ckingdon** [CSTARS/ckanext-ecosis#14]
different than the previous issue with this dataset .. the user has now updated Plant_ID to be string (i.e P01, P02, ... P80)

The metadata and data will not link on his browser/PC (mac OSX 10.7.5, firefox 30.0), yet it works on mine (ubuntu 12.04, chrome)

**Comment by jrmerz** [comment]
Nice catch.  Bug is fixed here: b93701c39d7a0f8d938776426d80731370915034.  Pushed to dev.
