### ISSUE TITLE
sandbox: problem occurs with long title?

### ISSUE THREAD

**Issue by ckingdon** [CSTARS/ckanext-ecosis#15]
On the sandbox, while Aidan was working with an existing dataset and he extended the title (maybe too long?) he got the following error:

- Package ID: 80bb16e2-73a8-432e-b145-16aad63de73e
- Message: Request Error. Failed to update dataset.
- Code: 9
- User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:43.0) Gecko/20100101 Firefox/43.0
- commit: 1884e1c0366892e94ceaec4315cf21ac6dc97145
- version: v1.2-130-g1884e1c
- branch: dev

He says that previously, if the title was too long, he got an error that told him something like "title is longer than XX characters"

**Comment by jrmerz** [comment]
Yup, looks like CKAN enforces a 100 character limit on titles.  I will add a better message to the input widget.

**Comment by jrmerz** [comment]
@ckingdon Should show error now.  Please test and close if fixed.

**Comment by ckingdon** [comment]
@jrmerz didn't work for me. When I tried to create a dataset with the name "this is an extremely long title this is an extremely long title this is an extremely long title ...", I got the following message:

- Package ID:
- Message: ValidationError:{u'Name': u'Name must be a maximum of 100 characters long'}
- Code: 6
- User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36
- commit: 6042a97c254398e9d1698c0c483bd883875924b6
- version: v1.2-132-g6042a97
- branch: master

I expected that the user would be given a warning that their title was > 100 characters and then be allowed to go back and edit, rather than getting a "computery" error message.

**Comment by jrmerz** [comment]
Hard refresh?  Looks like you are still running the old code on your browser.

**Comment by ckingdon** [comment]
clearing cache through developer tools fixed it
