### ISSUE TITLE
production: maybe another 'title too long' issue

### ISSUE THREAD

**Issue by ckingdon** [CSTARS/ckanext-ecosis#16]
Aidan got this error when I tried to save dataset on the Production side when extending a title.

- Package ID:
- Message: NotAuthorized:User aidanmazur not authorized to add dataset to this organization
- Code: 6
- User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:43.0) Gecko/20100101 Firefox/43.0
- commit: 1884e1c0366892e94ceaec4315cf21ac6dc97145
- version: v1.2-130-g1884e1c
- branch: master

Is there a title limit? If so, we should post it and have a catch for this.

**Comment by jrmerz** [comment]
Can you point me to the dataset?   Issue #15 is about title length, I will fix.  This looks like someone doesn't have access:

'NotAuthorized:User aidanmazur not authorized to add dataset to this organization'

**Comment by ckingdon** [comment]
http://data.ecospectra.org/dataset/determining-leaf-morphological-and-biochemical-traits-using-spectroscopic-calibrations-

**Comment by jrmerz** [comment]
This is was part of issue #15 and the wrong dataset being associated.
