### ISSUE TITLE
can't delete specific dataset

### ISSUE THREAD

**Issue by ckingdon** [CSTARS/ckanext-ecosis#17]
http://data.ecospectra.org/dataset/2014-bigbio-leaf-spectra

**Comment by jrmerz** [comment]
@ckingdon Should load now.  Feel free to close it everything looks good.

**Comment by ckingdon** [comment]
Nope. Still doesn't load for me .. still getting spinning wheel and "Preparing workspace ..."

**Comment by jrmerz** [comment]
Hard refresh?

**Comment by ckingdon** [comment]
I tried all the tricks to refresh, then killed chrome, then logged out and back into EcoSIS

**Comment by ckingdon** [comment]
works now after using Chrome developer tools to clear cache
