### ISSUE TITLE
After title change, exit button needs to update.

### ISSUE THREAD

**Issue by jrmerz** [CSTARS/ckanext-ecosis#18]

**Comment by jrmerz** [comment]
@ckingdon should update exit button now.  Please test and close if fixed.

**Comment by ckingdon** [comment]
@jrmerz still getting ...

404 Not Found
The resource could not be found.
Dataset not found

... when I exited after changing the title.

**Comment by jrmerz** [comment]
Hard refresh?

**Comment by jrmerz** [comment]
The button doesn't update until the save is finished.

**Comment by ckingdon** [comment]
after clearing the cache through chrome developer tools this now works
