### ISSUE TITLE
Creating Sandbox Set from JSON

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#20]
- Package ID:
- Message: NotAuthorized:User amazur not authorized to add dataset to this organization
- Code: 6
- User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:43.0) Gecko/20100101 Firefox/43.0
- commit: 1998747904b8a9c56f0c2d7ecf47551b872681f0
- version: v1.2-140-g1998747
- branch: dev

Attempted to create sandbox data set by uploading json file from production site

**Comment by jrmerz** [comment]
Can you email me the file?

**Comment by aidanmazur** [comment]
attached. Let me know if that ok


________________________________

**Comment by jrmerz** [comment]
didn't receive.  try emailing me directly.
