### ISSUE TITLE
Dev Search not working

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#21]
I am attempting to search on http://dev-search.ecospectra.org/#search, and the keywords are showing up in the dropdown bar as I type, but It will not allow me to search/nothing is coming up

**Comment by jrmerz** [comment]
Can you explain "It will not allow me to search/nothing is coming up" a little more?

**Comment by aidanmazur** [comment]
Sorry that was a little vague, the search page is remaining blank even after I type in key words and hit the search button. I have tried typing in multiple keywords and words that I know show up in titles but still nothing is working. Im working on Firefox 43.0.4 on Mac OSX 10.7.5.

**Comment by aidanmazur** [comment]
![dev-search](https://cloud.githubusercontent.com/assets/17035574/12966727/8377a8d8-d026-11e5-869a-5c57f7882511.jpg)

**Comment by aidanmazur** [comment]
Above screenshot is how screen is remaining after trying to search

**Comment by jrmerz** [comment]
Hummm.  Looks like a bug but I'm unable to reproduce locally.  Can you get your browser in the bad state, then click the hamburger menu icon (top right of browser), then 'Developer' -> 'Toggle Tools'. Once the dev tools are open, click the 'Console' tab.  Can you send me a screenshot of that?

**Comment by aidanmazur** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/17035574/12967132/857bcce2-d029-11e5-9d18-16d3d6d10efb.jpg)

**Comment by aidanmazur** [comment]
Dev Search is working fine for me now

**Comment by jrmerz** [comment]
There my be an asynchronous timing bug that only sometimes trips here.  I'm going to push an update in a little bit that should fix.

**Comment by aidanmazur** [comment]
I am now having the same problem as before, the Dev search is not working. It was working for me this morning. Note that I am navigating to the search page from the link on this page http://dev-data.ecospectra.org/#search

![screenshot](https://cloud.githubusercontent.com/assets/17035574/12988038/88d1b21c-d0c4-11e5-9824-4e8ad1ef45b3.jpg)

**Comment by jrmerz** [comment]
Frustrating, but I think we are getting somewhere.  Can you refresh your browser a couple times and try again?

**Comment by aidanmazur** [comment]
Refreshed a few times and still didn't work. Restarted my computer and now it is working again

**Comment by jrmerz** [comment]
When I make changes, you can always try a 'hard refresh'.  For firefox on
OSX I believe it's Cmd (Apple)+Shift+r".  The should make sure you are not
hitting your browsers cache.

On Thu, Feb 11, 2016 at 12:06 PM, aidanmazur <notifications@github.com>
wrote:

> Refreshed a few times and still didn't work. Restarted my computer and now
> it is working again
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CSTARS/ckanext-ecosis/issues/21#issuecomment-183043482>
> .
>



-- 
Justin Merz -- Center for Watershed Sciences -- University of California
Davis, CA 95616-8628

**Comment by jrmerz** [comment]
@aidanmazur everything look good on your end now?  If so I will close.

**Comment by aidanmazur** [comment]
Yes, search is working perfectly
