### ISSUE TITLE
Files Not downloading from dev search site

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#22]
I attempted to download CSV files from the dataset "Mazur Test" (http://dev-search.ecospectra.org/#result/995f8067-01b0-45b4-8e68-b07894dacad8), the function on the bottom, files did not download, and got this message 

![csv_download_error](https://cloud.githubusercontent.com/assets/17035574/13012714/fa871714-d171-11e5-93c5-917dfe81f5fa.jpg)

Tried with box checked to include metadata and also unchecked

**Comment by aidanmazur** [comment]
Im working on Firefox 43.0.4 on Mac OSX 10.7.5.

**Comment by jrmerz** [comment]
Yup, looks like I broke that.  Fix coming shortly.

**Comment by aidanmazur** [comment]
Working for other datasets im trying out, only that specific one isn't working for me

**Comment by jrmerz** [comment]
ok, patched.  Give it a go.

**Comment by aidanmazur** [comment]
Working now, thanks
