### ISSUE TITLE
"Data Viewer" missing Info

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#23]
Very small problem, on the production search site, under "data viewer" it says "Spectra 1 of" then nothing else on all of the datasets I've looked at

![dataviewerissue](https://cloud.githubusercontent.com/assets/17035574/13020654/455ef57a-d19c-11e5-9899-b5738bd2b319.jpg)

Minuscule, just thought I would mention it

**Comment by jrmerz** [comment]
Firefox?

**Comment by aidanmazur** [comment]
Firefox 44.0.2 on Mac OSX 10.7.5

**Comment by jrmerz** [comment]
thanks. pushed fix.  Try again?

**Comment by aidanmazur** [comment]
All fixed now, thanks

**Comment by jrmerz** [comment]
awesome!
