### ISSUE TITLE
Example Spectra Don't show up on Search Homepage

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#25]
Example spectra is not showing up on the search homepage (attachment). It seems to be a problem unique to me (it is working for clayton). 
![screen shot 2016-02-17 at 4 52 15 pm copy](https://cloud.githubusercontent.com/assets/17035574/13127789/059a7866-d597-11e5-83c6-fe7e1b8df258.jpg)

Working on Firefox 44.0.2 on Mac OSX 10.7.5

**Comment by jrmerz** [comment]
Think this is good now.  We might want to just switch to showing some interesting metrics.  Graph is kinda silly.
