### ISSUE TITLE
Error message when trying to create dev dataset

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#27]
- Package ID:
- Message: Request Error
- Code: 6
- User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:44.0) Gecko/20100101 Firefox/44.0
- commit: 6720f9c0c0f0dd5b772419182494aa79913ecaac
- version: v1.2-160-g6720f9c
- branch: dev

Creating a dataset on the dev site using a downloaded template from another dev dataset

**Comment by aidanmazur** [comment]
Still not allowing me to create dataset from template 

 - Package ID:
- Message: Request Error
- Code: 6
- User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:44.0) Gecko/20100101 Firefox/44.0
- commit: 58ae87c463d7b465c6a3e33d12ae76baf1ca9721
- version: v1.2-164-g58ae87c
- branch: dev

Using templated downloaded from "Productivity and Characterization of Soybean Foliar Traits Under Aphid Pressure" on the dev side

**Comment by jrmerz** [comment]
Can you email template file?

**Comment by aidanmazur** [comment]
Just emailed it to you

**Comment by aidanmazur** [comment]
- Package ID:
- Message: Request Error
- Code: 6
- User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.7; rv:44.0) Gecko/20100101 Firefox/44.0
- commit: 0ffd214d185827fe9c0407f122f03b399655975c
- version: v1.2-169-g0ffd214
- branch: dev

**Comment by jrmerz** [comment]
Are you able to setup a hangout/screen share so I can see what's up?

**Comment by aidanmazur** [comment]
Yes, I am available this afternoon to do that, sorry I was not in yesterday

**Comment by jrmerz** [comment]
Think we resolved.  Feel free to re-open if not.
