### ISSUE TITLE
Error 404 when exiting dataset on dev

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#28]
When I am exiting datasets on the dev site, sometimes instead of bringing me back to the normal page 

![screen shot 2016-02-23 at 5 45 35 pm copy](https://cloud.githubusercontent.com/assets/17035574/13270676/506aef84-da55-11e5-8f5f-12899f147cdc.jpg)

It gives me a '404 not found' error message

![screen shot 2016-02-23 at 2 30 40 pm copy](https://cloud.githubusercontent.com/assets/17035574/13270688/6c1f27ae-da55-11e5-8892-29b177da602a.jpg)

This has not been a problem on the production site, just the dev site, just thought I would bring it to your attention

**Comment by jrmerz** [comment]
Yup, fix coming

On Tue, Feb 23, 2016 at 3:47 PM, aidanmazur <notifications@github.com>
wrote:

> When I am exiting datasets on the dev site, sometimes instead of bringing
> me back to the normal page
>
> [image: screen shot 2016-02-23 at 5 45 35 pm copy]
> <https://cloud.githubusercontent.com/assets/17035574/13270676/506aef84-da55-11e5-8f5f-12899f147cdc.jpg>
>
> It gives me a '404 not found' error message
>
> [image: screen shot 2016-02-23 at 2 30 40 pm copy]
> <https://cloud.githubusercontent.com/assets/17035574/13270688/6c1f27ae-da55-11e5-8892-29b177da602a.jpg>
>
> This has not been a problem on the production site, just the dev site,
> just thought I would bring it to your attention
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CSTARS/ckanext-ecosis/issues/28>.
>



-- 
Justin Merz -- Center for Watershed Sciences -- University of California
Davis, CA 95616-8628

**Comment by jrmerz** [comment]
Good to close?
