### ISSUE TITLE
Refresh Failed

### ISSUE THREAD

**Issue by qjhart** [CSTARS/ckanext-ecosis#29]
- Package ID: cc09d078-ff74-4a1a-a79f-3e1655abdbf8
- Message: Request Error
- Code: 19
- User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.63 Safari/537.36
- commit: 1263e6bdfb8e5f3f63f0f0fc42b08ef6a9889880
- version: v1.3-1-g1263e6b
- branch: master

[Any Additional Info Here]

**Comment by jrmerz** [comment]
Looks like the aliases was being set to array instead of hash.

**Comment by jrmerz** [comment]
Ok, fixed pushed to dev & prod.  Thanks for the catch!
