### ISSUE TITLE
international .csv files?

### ISSUE THREAD

**Issue by ckingdon** [CSTARS/ckanext-ecosis#3]
Related to dataset AspenCompetitionGarden2015, I poking around with some other .csv files from this user.

His .csv files use a ; (semi-colon) as the separator, and floating point values in the file use a , (comma, i.e. 4.5 is 4,5).

This threw me when I tried to do some things on my own PC (not on EcoSIS).

**Comment by jrmerz** [comment]
@ckingdon see my comments on issue #2 

As for the 4,5 instead of 4.5... we will need to discuss this further.  For now it will be on the user to supply correct integer values.

**Comment by ckingdon** [comment]
I like giving options for the separator. Prabu pointed out that he thinks CSV is becoming more and more generic and many take the C to mean 'character' rather than 'comma'.

Regarding use of , instead of . for floating point numbers, I think we'll eventually need to address this at some point. Many in the international community use this format

**Comment by jrmerz** [comment]
Think we need to make this a discussion in trello.  Cause it looks like a can-o-worms: https://en.wikipedia.org/wiki/Decimal_mark#Examples_of_use
