### ISSUE TITLE
Opening 'stats' under 'data viewer' changes web page size

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#32]
after clicking 'stats' button and viewing spectra under 'data viewer', when user then clicks out of 'stats', the spectra changes back to original spectra, but the page appears to reformat and the graph goes off screen. This is happening for me on both firefox and chrome.

Before
![before](https://cloud.githubusercontent.com/assets/17035574/13851169/1d43e57e-ec2b-11e5-8529-a8ebc2908bf7.jpg)

After

![after](https://cloud.githubusercontent.com/assets/17035574/13851175/226ce7e4-ec2b-11e5-8034-2a1bd546e90d.jpg)

**Comment by jrmerz** [comment]
I don't think this is an issue anymore.  The metadata table is now below the graph.  Please re-open if that's not the case.
