### ISSUE TITLE
Template DOI carry-over

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#33]
When template is downloaded from dataset that has been assigned a DOI, then the template is used to create a new dataset, the DOI is applied so that the newly created dataset can no longer be edited

**Comment by aidanmazur** [comment]
This is also the case when a dataset is created using a template from a dataset that has a pending DOI request, then the dataset newly created will also automatically have a pending DOI request, which shows up on the EcoSIS DOI admin page when dataset is created

**Comment by jrmerz** [comment]
Ok, DOI attributes should be left off of import.

**Comment by aidanmazur** [comment]
Looks good
