### ISSUE TITLE
No Datasets shown on sandbox

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#34]
On sandbox search (http://dev-search.ecospectra.org/#home), It appears as though there are no datasets uploaded or available to search

**Comment by aidanmazur** [comment]
On both Chrome used on windows 7 and Firefox 46.0.1 on OS X El Capitan 10.11.4

**Comment by jrmerz** [comment]
Thanks.  I think I was messing with the database and restarted it, then the webapp failed to reconnect.  I restarted the server and all is good now.
