### ISSUE TITLE
Dataset information not visible on dev importer using chrome on windows

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#35]
On sandbox data importer, when I try to view the dataset information, the dataset metadata shows up blank, however the metadata scores (eg 7/7) show that fields are filled in, and when you exit the dataset, all of the information shows up on the dataset summary page. 

This problem is only occurring when I use Chrome Version 51.0.2704.84 m on Windows 7

**Comment by aidanmazur** [comment]
Refreshing and hard refreshing (Ctrl Shift R) does not make information appear

**Comment by aidanmazur** [comment]
Also occurs when using Internet Explorer 11 and Firefox 30.0 when "Manage Dataset" button first pressed, but is resolved with a refresh of the web page. NOTE: this is only occurring when using EcoSIS on a PC with Windows 7, does not occur when using Max OS X 10.11.4

**Comment by aidanmazur** [comment]
When this occurs, this is what the page looks like, take note of the DOI section

![screencapture-docker-dev-data-ecosis-org-import-1466110490628](https://cloud.githubusercontent.com/assets/17035574/16132876/c00f72fe-33da-11e6-98c4-704655070ef6.png)

**Comment by jrmerz** [comment]
Can you give me the dataset url?  I am unable to reproduce.

**Comment by aidanmazur** [comment]
http://dev-data.ecospectra.org/import/?id=bd069000-f9a1-496c-93a8-3bcff7900167

The first time I enter the dataset, information shops up, but if I exit dataset and then "Manage Dataset" information is gone and I get page that I screenshotted, and continues to happen even after exiting and re entering again

**Comment by aidanmazur** [comment]
It is happening for me on all dev datasets that I enter

**Comment by jrmerz** [comment]
Sorry, pushed a bad build.  Give a hard refresh, should be working now.

**Comment by aidanmazur** [comment]
Looks good
