### ISSUE TITLE
Cannot delete dataset even after DOI removed

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#36]
- Package ID: 86765256-9081-4489-970f-554c1bec76c1
- Message: Request Error
- Code: 5
- User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
- commit: a913b060585fdb878a695e440e9bda8493164940
- version: v1.4-40-ga913b06
- branch: dev

Removed DOI using URL, but EcoSIS will still not let me delete dataset, saying it says dataset still has DOI

**Comment by jrmerz** [comment]
@aidanmazur great catch, this was actually a very bad bug.  Fix pushed.

**Comment by aidanmazur** [comment]
Looks fixed, Thanks
