### ISSUE TITLE
Unable to publish dataset on docker dev site when email requested

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#37]
Unable to publish dataset "Docker Test Dataset Mazur 1.0" on the docker dev importer site, when the "Email me when the dataset is available in search" box is checked. When I UNchecked the box, dataset published almost immediately

**Comment by jrmerz** [comment]
Ya, the dockers email is fubar, I'm still trying to discover why...

**Comment by jrmerz** [comment]
@aidanmazur email should be running on docker.  give it a go

**Comment by aidanmazur** [comment]
email being sent when publishing on docker-dev and dataset publishing
