### ISSUE TITLE
DOI status resetting on Dataset importer 

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#38]
I requested a DOI for the dataset "Sandbox Test Dataset Mazur 1.0". I then denied the DOI pending revision. On the dataset importer page, under the DOI field, it has reset to the original DOI request message and box and does not mention that the DOI was denied pending revision

**Comment by aidanmazur** [comment]
requested DOI for dataset "Sandbox Test Dataset Mazur 2.0", I exited dataset and did a hard refresh, when I reentered dataset the DOI status had reset to original DOI message and did not show that DOI had been requested, The request can still be seen on the DOI admin page

**Comment by jrmerz** [comment]
Fix has been pushed to dev-data.

**Comment by jrmerz** [comment]
@aidanmazur let me know if this is working and let's close.

**Comment by aidanmazur** [comment]
Having same problem. The DOI status on the dataset overview page is updated, but within the dataset the DOI metadata field resets to "Request Dataset" anytime you exit and reenter no matter the actual DOI status

**Comment by jrmerz** [comment]
Sheepish grin... I push the fix w/o a new build.  K, fix should be fixed 'for real' this time.

**Comment by aidanmazur** [comment]
Everything looks good for this now!
