### ISSUE TITLE
Cannot delete dataset due to DOI but no DOI applied-on Docker

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#39]
- Package ID: 37f84bf6-b6e2-462a-ab1b-eb263cc6ea29
- Message: Request Error
- Code: 5
- User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
- commit: 62bcca7cb256859bc474cf0e96ced78d7c17dd03
- version: v1.4-44-g62bcca7
- branch: (detached from a913b06)

having similar problem as issue #36 on docker dev.

on datasets "Docker Test Dataset Mazur 1.0" and "Docker Test Dataset Mazur 2.0"

**Comment by jrmerz** [comment]
Is this issue related to http://docker-dev-data.ecosis.org/, http://docker-prod-data.ecosis.org/ or both?

**Comment by aidanmazur** [comment]
I have only tested dev, will try it out on prod

**Comment by jrmerz** [comment]
It's ok, I can tell you prod will definitely fail :)

**Comment by jrmerz** [comment]
@aidanmazur this is working for me on dev-data.  You?

**Comment by aidanmazur** [comment]
working for me now as well
