### ISSUE TITLE
add user information on dataset tab

### ISSUE THREAD

**Issue by ckingdon** [CSTARS/ckanext-ecosis#4]
I know you can see all activity on another tab, but this would be a nice feature on the dataset tab.

So, this ... 

Last Updated	October 28, 2015, 19:42
Created	October 28, 2015, 17:11

would become ...

Last Updated	October 28, 2015, 19:42 by jrmerz
Created	October 28, 2015, 17:11 by Lorenzo Cotrozzi

**Comment by jrmerz** [comment]
feature discussion, moved to trello: https://trello.com/c/wm40n7Nn/133-add-user-information-on-dataset-tab
