### ISSUE TITLE
Docker Dev Search Links mismatched

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#41]
On Docker Dev search site (http://docker-dev-search.ecosis.org/) the link for data uploaders (both in the middle of the page and on the bottom) link to http://data.ecosis.org/ instead of http://docker-dev-data.ecosis.org/.

**Comment by aidanmazur** [comment]
Also link on http://docker-dev-data.ecosis.org/ for the "EcoSIS search" sends to http://dev-search.ecospectra.org/ instead of http://docker-dev-search.ecosis.org/

**Comment by jrmerz** [comment]
ok, all docker-dev-[search | data] links should be fixed
