### ISSUE TITLE
Cannot open or create datasets on Dev

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#42]
When I attempt to open datasets on dev-data.ecospectra.org I get a "404 not found" error. Also the case when I try to create datasets. Happening on both Firefox and Chrome on Mac OS X 10.11.4

**Comment by jrmerz** [comment]
Oops, copied bad config from 'old' dev.  One sec

**Comment by jrmerz** [comment]
ok, should be up

**Comment by aidanmazur** [comment]
looks good thanks!
