### ISSUE TITLE
Dataset not publishing when "send email" option checked

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#43]
Tried publishing dataset with the option "Email me when the dataset is available in search" is checked and the dataset was not published and no email is sent. When I tried publishing dataset without box checked it published almost immediately

**Comment by jrmerz** [comment]
Bad email setup.  Try now.

**Comment by jrmerz** [comment]
@aidanmazur let me know if this is working and we can close.

**Comment by aidanmazur** [comment]
looks good
