### ISSUE TITLE
Cannot toggle visibility options when adding dataset through viewing an Organization

### ISSUE THREAD

**Issue by adjablonski** [CSTARS/ckanext-ecosis#45]
If I go upload a dataset via "Datasets->Add Dataset", I am able to select my organization and then select the visibility as public or private. However if I upload a dataset via "Organizations->UW Enspec->Add Dataset", my group is preselected but I am unable to select visibility as public or private. Changing the organization selection (either to a different organization or none, and back to UW-Enspec) still doesn't allow me to change visibility options.

**Comment by jrmerz** [comment]
@adjablonski nice catch.  This was actually 2 bugs.  First, the **visibility** selector was not being updated when the org was selected (you can only have private packages that are a member of a organization).  Second, the initial organization selector state was not being set if the **group** url parameter was set.

Both should be fixed as of commit above (pushed to dev).  Give them a try and let me know how things look on your end.

**Comment by jrmerz** [comment]
@adjablonski ping

**Comment by aidanmazur** [comment]
tested this one, working fine now

**Comment by jrmerz** [comment]
@aidanmazur thanks!
