### ISSUE TITLE
Deleting datasets results in bug

### ISSUE THREAD

**Issue by adjablonski** [CSTARS/ckanext-ecosis#46]
Just trying out a hard delete on the the dev side of Ecosis. I'm wondering if it's because a DOI has been attached?

Error: TypeError:canUpdate() takes exactly 3 arguments (1 given)

 Package ID: 87d073f4-2069-4b08-aa44-527b2a5cf5a4
- Message: Request Error
- Code: 5
- User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
- commit: 9f172bbc1c99b97d87bd2b412172232aefab45d3
- version: v1.7-5-g9f172bb
- branch: dev

**Comment by jrmerz** [comment]
@adjablonski where were you deleting the dataset from?  IE, which button?  In the latest release, the delete button is no longer visible after a DOI is applied on the EcoSIS Importer - Basic Information page.

**Comment by adjablonski** [comment]
@jrmerz I was attempting to delete the dataset from the "Manage Dataset" page on the EcoSis sandbox. I've attached a screenshot with a red box showing where I found the button.

![delete_bug](https://cloud.githubusercontent.com/assets/20327735/17374788/d750943e-5973-11e6-93a4-97e1f544fce0.png)

**Comment by jrmerz** [comment]
That looks like old code.  Can you give a hard refresh, then make sure the bottom is tagged with version v1.7-6-g9f480e9.

Note, since a DOI is applied, I just pushed an update that will throw an alert about not being able to update the dataset when you first load.  I am actively working on this.

**Comment by adjablonski** [comment]
I just checked it out now and the delete dataset button is gone. Code version is up to date. I did a hard refresh and the button returned. After playing around some more (closing/restarting chrome) the button is gone again. It doesn't show up on IE either.

Your alerts about not being able to update are showing up as well. I'll check back later tonight and see how it goes.

**Comment by jrmerz** [comment]
Closing for now, reopen if problem crops up again.
