### ISSUE TITLE
"Other" categories don't reveal the specifics when viewed in search

### ISSUE THREAD

**Issue by adjablonski** [CSTARS/ckanext-ecosis#47]
I'm not sure if this is a bug or an intentional design or what. But if I select "other" categories for options under measurement type, an additional box pops up allowing you to specify what "other" is. See the first image: 

![other_explanation](https://cloud.githubusercontent.com/assets/20327735/17416701/05fcd41e-5a55-11e6-98c3-1a36c362b699.png)

However when I view this on the search side, those explanation fields don't actually show up. Maybe this isn't a bug, but as far as I can tell there is no way for someone searching/downloading this data to figure out what exactly the "other" category constitutes. The image below is what displays in search.

![other_search](https://cloud.githubusercontent.com/assets/20327735/17416771/69cce830-5a55-11e6-9fce-b2f24a1061dd.png)

**Comment by jrmerz** [comment]
Another nice catch.  Fixed pushed to dev.  Let me know if things look ok.

**Comment by jrmerz** [comment]
@adjablonski ping

**Comment by aidanmazur** [comment]
Other values now showing up, this is good to close
