### ISSUE TITLE
Unable to publish dataset on dev

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#48]
When I try to publish dataset on dev I get error message:

 - Package ID: 3eca6f84-b10c-4c47-849d-3643079529d7
- Message: Request Error. Error publishing dataset.
- Code: 12
- User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
- commit: 0fe11fb7f583fb2182fe6c2edc6930eee9ef140d
- version: v1.7-12-g0fe11fb
- branch: dev

Have tried both Chrome  52.0.2743.116 and firefox 47.0
Tried with "Email me when the dataset is available in search. " selected and not 
Tried with both existing and new datasets

**Comment by jrmerz** [comment]
@aidanmazur you are a bug finding machine.  Bug with generating citation with single author.  Should be fixed.  Give it a try.

**Comment by aidanmazur** [comment]
Datasets are publishing fine now. However, in the publishing tab at the top, the green check mark is immediately changed to the yellow triangle notice and under "search Status" it continues to say that dataset has been "updated since last publish" even if that is not the case

**Comment by jrmerz** [comment]
Nice catch.  When no Organization is set, I make sure the private flag is set to false.  I was not checking it this flag was already false and the set command automatically was calling save.  Thus, on load, the dataset become one save behind the published version.

I have pushed fix to dev.  Let me know what you see.

**Comment by aidanmazur** [comment]
If there is an organization associated with the dataset then the the green check mark remains after publishing, if there is no organization then green check mark turns to yellow triangle even if no changes happen post publishing

**Comment by jrmerz** [comment]
Yes, that's what I think I fixed.  can you give a hard refresh and see if that is still the case?

**Comment by aidanmazur** [comment]
Looks good

**Comment by aidanmazur** [comment]
Feel free to close this immediately because it may not be a problem, but I removed the DOI from the dataset "DOI citation testing" and now the green publishing checkmark turns to yellow after publishing. It is not happening on other datasets, only on dataset with removed DOI, so a very niche group which isnt a problem because we wont be removing DOIs on production, just wanted to let you know

**Comment by jrmerz** [comment]
Can you provide the dataset link?

**Comment by aidanmazur** [comment]
http://dev-data.ecospectra.org/import/?id=37ea9da6-ff5c-484a-b655-7625fefea1c6

**Comment by jrmerz** [comment]
It's always good to investigate these kind of bugs.  There was a larger issue tripping the bug described here.  Please try again and let me know if things work as expected.

**Comment by aidanmazur** [comment]
Problem fixed, thanks
