### ISSUE TITLE
metadata and data file records truncated

### ISSUE THREAD

**Issue by ckingdon** [CSTARS/ckanext-ecosis#5]
noticed on dataset "2015 Summer Conductance"

For "Conductance_Spec_Means_20150827.csv" resource, importer doesn't see the last spectrum, which is "L39" under the leaf column.

Also, while importing "Conductance_Metadata.xlsx", the last two records were dropped.

**Comment by jrmerz** [comment]
This was a nice catch.  I think I have the bug nailed down.  Will be pushing fix soon.

**Comment by jrmerz** [comment]
pushed.
