### ISSUE TITLE
error create basic info from template

### ISSUE THREAD

**Issue by annakat** [CSTARS/ckanext-ecosis#50]
- Package ID:
- Message: Request Error
- Code: 6
- User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/601.7.8
- commit: f362857d4fdc1c2df2aabe7ec10ea9e80005c966
- version: v1.7-19-gf362857
- branch: (detached from 1737f04)

**Comment by jrmerz** [comment]
@annakat Thanks for posting the issue!  Any chance you can attached the .json template file you are using to create dataset with?  It will help with debugging.

**Comment by annakat** [comment]
{
    "maintainer": "",
    "author": "Anna K Schweiger, Anna K Schweiger",
    "private": false,
    "maintainer_email": "anna.k.schweiger@gmail.com",
    "author_email": "anna.k.schweiger@gmail.com",
    "extras": {
        "Measurement Units": "%",
        "Wavelength Units": "nm",
        "Funding Source Grant Number": "NSF 1342872",
        "Measurement Quantity": "Reflectance",
        "Theme": "Ecology",
        "Processing Interpolated": "Yes",
        "Instrument Serial Number": "HI: 1152050",
        "Foreoptic Type": "Leaf Clip",
        "Instrument Model": "HR-1024i",
        "Processing Averaged": "No",
        "Instrument Manufacturer": "Spectra Vista Corporation",
        "Location Name": "East Bethel, MN",
        "Acquisition Method": "Contact",
        "Processing Information Details": "resampled to 1 nm spectral resolution, jumps between sensors corrected",
        "Target Status": "Fresh",
        "Processing Resampled": "Yes",
        "Light Source": "Lamp",
        "Target Type": "Leaf",
        "resourceUpdateCount": "1"
    }
}

**Comment by annakat** [comment]
... Could also have been caused by the bounding box I drew on the map. The second attempt worked.

**Comment by jrmerz** [comment]
Interesting.  Would still like to investigate.  So you drew a bounding box, then attempted to create dataset via template?

**Comment by annakat** [comment]
I first uploaded the template, then drew the bounding box.

**Comment by jrmerz** [comment]
Ok.  Sorry to ask so many questions, trying to see what tripped the error... What bounding box (general area) did you draw?

**Comment by annakat** [comment]
"geojson": "{\"type\":\"Polygon\",\"coordinates\":[[[-93.22667598724365,45.41652746358743],[-93.22667598724365,45.3822958616878],[-93.14633846282959,45.3822958616878],[-93.14633846282959,45.41652746358743],[-93.22667598724365,45.41652746358743]]]}",

**Comment by annakat** [comment]
Saved it as a new template, it's a small area (~ 25 km2), Cedar Creek.

**Comment by annakat** [comment]
Okay, I uploaded another dataset using the same procedure. Worked like a charm.

**Comment by jrmerz** [comment]
Closing, feel free to reopen if this happens again.
