### ISSUE TITLE
Not allowing deletion of resource files

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#52]
I am attempting to delete 2 resource files (the .zip and the .JPG files) from the dataset "Mazur Test Dataset 1.8" (http://dev-data.ecospectra.org/dataset/mazur-test-dataset-1-8), but they keep reappearing after I exit dataset and show up on the search side.

**Comment by aidanmazur** [comment]
Just tried to delete individually (before I was selecting then trying to delete all selected) and got this error

 - Package ID: 37ea9da6-ff5c-484a-b655-7625fefea1c6
- Message: Request Error. Server error deleting resource.
- Code: 17
- User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
- commit: 1ef9f1798ec0e4cb8b0fafb98130985ba8bd6f87
- version: v1.8-15-g1ef9f17
- branch: dev

**Comment by aidanmazur** [comment]
Figured it out, the dataset was pending DOI, so resource files could not be edited.

**Comment by jrmerz** [comment]
This should not throw and error.  It's good the backend is rejecting the call for delete, but UI should not be showing the delete button in the first place.

Nice find.  Let's leave open util I fix.

**Comment by jrmerz** [comment]
@aidanmazur fix pushed.  Should not show delete/edit buttons after DOI is requested.  Will now reload page after DOI is requested/cancelled to make sure UI is in correct state.
