### ISSUE TITLE
Modify date not updating

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#53]
I am editing the resource file "MultipleSheet_Test_Mazur_v1.xlsx" within the dataset Mazur Test Dataset 1.8 (http://dev-data.ecospectra.org/import/?id=37ea9da6-ff5c-484a-b655-7625fefea1c6#current-resources) but the modify date is not updating, still showing the same date and time as the created date. 

(also as side note the time appears to be off)

**Comment by jrmerz** [comment]
@aidanmazur The modified date is when the file was last modified.  Not when it is last configured.   Modification timestamps to resource configurations are not currently tracked by the system.  I agree this is confusing and perhaps something we should remove.

**Comment by aidanmazur** [comment]
@jrmerz I guess I am confused on what changes would update the modified time?

**Comment by jrmerz** [comment]
@aidanmazur pushed to dev
