### ISSUE TITLE
Photo linking not working

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#54]
On dataset "Mazur Test Dataset 1.8" (http://dev-data.ecospectra.org/import/?id=37ea9da6-ff5c-484a-b655-7625fefea1c6#current-resources)

Photos not linking to spectra. Tried a couple different things:
Tried adding separate resource file with just unique id and photo id but didnt link
Now tried adding Photo field to metadata sheet, but photos are not showing up. 

In the resource editor, a link "Spectra Photo" shows up under the spectral graph but when you click on it it directs you to a 404 error page

**Comment by jrmerz** [comment]
@aidanmazur fix pushed to dev (c1941ee6bf4a0a5755a7099476d68f71a72f14bf)

**Comment by aidanmazur** [comment]
looks good
