### ISSUE TITLE
Superscripts not showing up in units on resource files

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#56]
Some of the units provided in the metadat sheet are (g/cm²), however both in importer and on search (under data viewer) the superscript 2 is being omitted

**Comment by aidanmazur** [comment]
See dataset ANGERS Leaf Optical Properties Database (2003)

http://data.ecosis.org/import/?id=2231d4f6-981e-4408-bf23-1b2b303f475e#current-resources

https://ecosis.org/#result/2231d4f6-981e-4408-bf23-1b2b303f475e

**Comment by jrmerz** [comment]
k, this is an interesting one.  Proly needs to become a trello card.  Basically there were bad unicode characters that were being passed and crashed my parsers.  So I went and only allowed ascii strings (very limited subset of characters).  This was out of time constraints.  I should be able to encode all characters as UTF-8 and keep such characters as super scripts.  This will need to be heavily tested and I think should be moved to v1.9.

**Comment by aidanmazur** [comment]
card made
