### ISSUE TITLE
dev importer server error

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#57]
no able to go to "datasets" on dev data importer site. Instead throws a server error. On the tab it reads "Error 500" and on the page it reads "Server Error An internal server error occurred"

I AM able to go to dev data importer home page, but not able to access datasets. 

This is on windows 7 using Firefox 47.0.1

**Comment by jrmerz** [comment]
So mongodb tanked.  Poking around it looks like it ran out of memory but hard to tell.  There was no swap space enabled for the VM (badness) which may have been the issue as we use all of our 4GB between the 4 sites / 10 docker containers.  I have enabled swap space. This is slightly a blind fix, but I feel a reasonable one.  @aidanmazur @ckingdon I'm going to close this for now, but let me know if you see this happen again.
