### ISSUE TITLE
push to search email

### ISSUE THREAD

**Issue by ckingdon** [CSTARS/ckanext-ecosis#6]
When the user pushed dataset to search, the pop up says "no email will be sent", though the user had the box check to send a notification email. The user *did* get the email when the dataset made it to search.

**Comment by jrmerz** [comment]
This will be interesting to replicate.  Any additional information would be welcome.  Browser / OS etc.

**Comment by jrmerz** [comment]
@ckingdon ping.  Any additional information on this?

**Comment by ckingdon** [comment]
I'll have to wait until Aidan takes a shot at this when he next pushes a dataset. I'll email this github link to him so he knows to check.

**Comment by ckingdon** [comment]
Aidan tells me this is still happening .. will get more info when he joins the group
