### ISSUE TITLE
Metadata is not linking on 1 measurement

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#60]
In dataset "Time Series Test" the metadata is not linking for only one spectral measurement (Meter0). Looked at formatting on the excel side and looks to be the same as the other names. Re uploaded resource file a couple times and still isnt linking, but only that one measurement

**Comment by aidanmazur** [comment]
dataset is on dev http://dev-data.ecospectra.org/dataset/time-series-test

**Comment by jrmerz** [comment]
fix pushed to dev, let me know how things look on your end.

Just FYI, this was due to a bug when parsing the sheet with a starting blank column(s).  The system should handle this.  Bug fixed, so things should be good now.  But please test.

**Comment by aidanmazur** [comment]
Original problem fixed

Tested (on same dataset) by adding 1 blank column on the Run5Reflectance sheet and 2 blank columns on the Metadata sheet and re uploading resource file and am running into issues. It is not formatting the Run5Reflectance, ie no spectra are showing up

**Comment by jrmerz** [comment]
you and your 'testing' ;)

Let me take a look

**Comment by jrmerz** [comment]
So data needs always be aligned against the left most column. ie column A must be the start of the data.  We allow for blank rows, but not blank columns.
