### ISSUE TITLE
Ordering function does not appear to be working

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#61]
Under the 'Advanced' tab there is the 'ordering' tab. I am working with the dataset "formatting time series data" (http://dev-data.ecospectra.org/dataset/formatting-time-series-data) and am trying to order the data by different fields but it does not appear to be doing anything (on data previewer [importer], data viewer [search] or on the downloaded csv file [search]). I have tried different combos of the "order by" and "order type" choices with no changes seen

**Comment by jrmerz** [comment]
OK, a couple things on this one.  First, there were bugs, I think i have fixed them.  Second, sorting will only show on the search side.  So you have to push to see things sorted.  Third, if you want to sort by the numeric value, (ie not alphabetical), you need to set the sort type to 'numeric'.  That tells the server how to interpret the values.

http://dev-search.ecospectra.org/#result/def322a8-beb0-4f31-9601-edb73e547f11

Let me know how things look on your end.

**Comment by aidanmazur** [comment]
Sorting function under the Ordering tab appears to be working fine on my end
