### ISSUE TITLE
Issue with Data Viewer on Search

### ISSUE THREAD

**Issue by aidanmazur** [CSTARS/ckanext-ecosis#63]
Referring to dataset "Productivity and Characterization of Soybean Foliar Traits Under Aphid Pressure" (https://ecosis.org/#result/cdbb6b09-b481-4022-a0da-ad95a8b085d8)

The data viewer is repeating the graph (spectra) and metadat for spectra 705 until the end

**Comment by jrmerz** [comment]
Give it a go now

**Comment by aidanmazur** [comment]
Looks perfect, thanks

**Comment by aidanmazur** [comment]
Same issue (The data viewer is repeating the graph (spectra) and metadat for spectra 705 until the end) on dataset "Fresh test metadata fields" on Dev (http://dev-search.ecospectra.org/#result/40b7b3d6-9519-48f9-80da-fc775c292d1a)

**Comment by jrmerz** [comment]
@aidanmazur ok, give it a go now

**Comment by aidanmazur** [comment]
Looks good thanks
