### ISSUE TITLE
No "urban" or "other" option in Ecosystem Type

### ISSUE THREAD

**Issue by skelsey4** [CSTARS/ckanext-ecosis#65]
Would it be possible to add an "Urban" option or do an "Other" option with an additional description for the Ecosystem type?  My lab will be posting reflectance spectra of inland waters in the future, but at the moment we have some spectra from a side project that involved asphalt, brick, and paving stone surfaces.  I think there's at least one other submission on Ecosis that works with man-made materials as well.

**Comment by serbinsh** [comment]
Similarly there isn't an Arctic tundra ecosystem type which is a distinct PFT/ veg type

**Comment by jrmerz** [comment]
@ckingdon FYI

**Comment by jrmerz** [comment]
pushed to prod
