### ISSUE TITLE
Add license as compulsary field for public website/DOI request

### ISSUE THREAD

**Issue by amrutavidwans** [CSTARS/ckanext-ecosis#82]
Hi Justin, I discussed with Phil and he is on-board with adding license as compulsory field. I have tagged it as 'enhancement' and 'ckan-2.9' for now, but feel free to change it to appropriate ones.
Thanks.

**Comment by jrmerz** [comment]
deployed to dev.  

I made license a required field for all new packages going forward.  Additionally, there is no longer a 'no license' option.

**Comment by amrutavidwans** [comment]
Closing and creating a new bug for this.
