### ISSUE TITLE
Providing Location Name does not create a bounding box on the map

### ISSUE THREAD

**Issue by amrutavidwans** [CSTARS/ckanext-ecosis#84]
Providing Location Name in Location section in the Basic Information does not create a bounding box on the map. 
Additionally, when the Location Name is provided and dataset is published, the Location appears as Not Provided.

![Screen Shot 2021-11-24 at 3 02 57 PM](https://user-images.githubusercontent.com/12546910/143312491-41ac45a6-fe33-4824-9e12-2fceadf76791.png)

**Comment by jrmerz** [comment]
Fix implemented here CSTARS/ecosis@bf16894bfa3da86330db691a2121068f2cad801d Accidently tagged commit message to #85

**Comment by amrutavidwans** [comment]
As per our discussion, this is not the intended use.
